include: all_lint_rules.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # Otherwise cause the import of all_lint_rules to warn because of some rules conflicts.
    # We explicitly enabled even conflicting rules and are fixing the conflict
    # in this file
    included_file_warning: ignore

linter:
  rules:
    cascade_invocations: false
    prefer_double_quotes: false
    always_specify_types: false
    unnecessary_final: false
    prefer_expression_function_bodies: false
    always_put_required_named_parameters_first: false
    avoid_as: false
    flutter_style_todos: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    avoid_annotating_with_dynamic: false
    always_use_package_imports: false
    no_default_cases: false
    one_member_abstracts: false
